// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Inventario.Transaccion.Infraestructura.Persistencia;

#nullable disable

namespace Sistema.Inventario.Transaccion.Migrations
{
    [DbContext(typeof(TransaccionDbContext))]
    [Migration("20260406155619_EsquemaInicialInventarioTransaccionesBD")]
    partial class EsquemaInicialInventarioTransaccionesBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Inventario.Transaccion.Dominio.Entidades.TransaccionEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Detalle");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PrecioTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioTotal")
                        .HasComputedColumnSql("CAST((Cantidad * PrecioUnitario) AS DECIMAL(10,2))", true);

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductoId");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoTransaccion");

                    b.HasKey("Id");

                    b.ToTable("Transacciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transacciones_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_Transacciones_PrecioUnitario", "[PrecioUnitario] >= 0");

                            t.HasCheckConstraint("CK_Transacciones_TipoTransaccion", "[TipoTransaccion] IN (N'Compra', N'Venta')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
